### ISSUE TITLE
Backend Setup

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] setup client error component 
- [x] setup error-middleware component
- [ ] Setup middleware [C][R]UD for log-in/register
    - [x] create a post request
        - [x] add error handling to prevent repeated username
        - [x] add error handling for a secure password 
        - [x] create a token 
        - [x] create an sql which will send both the username and token to the database
        - [x] send out the status code and parse the new row
     - [x] create a get request 
        - [x] add error handling for invalid login
        - [x] create an sql which selects the matching userId
        - [x] send out status code and parse the requested row
- [ ] Setup middleware for [C][R]U[D] on images
    - [x]  create a post request
        - [x] add error handling for corrupted images
        - [x] create an sql to insert the image url and caption
        - [x] send out status code and parse the new row
     - [x] create a get request 
        - [x] add error handling
        - [x] create an sql to select all rows
        - [x] send out status code and parse all rows
     - [x] create a get request 
        - [x] add error handling
        - [x] create an sql to select all rows
        - [x] send out status code and parse the selected row
     - [x] create a delete request 
         - [x] add error handling
         - [x] add an sql to delete the matching imageId
         - [x] send out status code and parse selected row
 - [x] Setup middleware for [C][R]U[D] on mp3
     - [x] create a post request
         - [x] add error handling for corrupted mp3 urls
         - [x] create an sql to insert the mp3 url and caption
         - [x] send out status code and parse new row
    - [x] create a get request
        - [x] add error handling 
        - [x] create an sql to insert mp3 url and caption
        - [x] send out status code and parse all rows  
    - [x] create a get request
        - [x] add error handling 
        - [x] create an sql to insert mp3 url and caption
        - [x] send out status code and parse selected row
    - [x] create a delete request
        - [x] add error handling
        - [x]  create an sql to delete the matching songId
        - [x] send out status code and parse selected row
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
