### ISSUE TITLE
Issue 6: User can delete a selfie

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users may have not liked the selfie they have taken so giving them the option to delete it by clicking the key "D" on desktop, doing so a model with a prompt with the two button "confirm and cancel"

User can delete a picture taken

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Ill be creating a model with a button to send a fetch reqi componentand update the foto component so the model component is conditionally rendered when a specific key has been pressed.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="634" alt="Screenshot 2023-05-17 at 12 00 44 AM" src="https://github.com/Lambpato/LSP/assets/34325124/296d3803-24b1-4908-a5eb-78c0bc1a37ec">
<img width="819" alt="Screenshot 2023-05-17 at 12 03 19 AM" src="https://github.com/Lambpato/LSP/assets/34325124/3af4502b-e1aa-4182-a9a5-ee30fa077cbf">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component that 
    - [x] displays a model with a prop to change the text of the model
    - [x] a confirm button that 
        - [x] sends a fetch request with a delete method
        - [x] hides the model
    - [x] a cancel button which hides the model
- [x] Update the photos component to 
       - [x]  listen for keyPress on 'D' 
       - [x] return the model component if pressed

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
