### ISSUE TITLE
Issue 7: User can store mp3 files

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="819" alt="Screenshot 2023-06-02 at 2 48 04 PM" src="https://github.com/Lambpato/LSP/assets/34325124/0b197447-1f4b-4c01-9eef-96823ba8e427">
<img width="771" alt="Screenshot 2023-06-02 at 2 48 22 PM" src="https://github.com/Lambpato/LSP/assets/34325124/5b6d489f-c3f7-4844-a6bb-26ec926249c2">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component that contains a form that
    - [x] has "New Song" as the header
    - [x] Requires all inputs to be submitted
    - [x] Takes in fromData
    - [x] Takes in a name 
- [x] Create a component that
    - [x] Sends a post fetch request to '/api/songs/upload'

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
