### ISSUE TITLE
Issue 8: User can view list of saved songs

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#15]
## ⚙️ Features

> ##### Which feature is affected by this update?

Similar the Photos Page , this will display a list with the users songs as well as displaying the length of the song
## 📐 Plan

> ##### Summary of the technical approach to be taken.

Ill be creating a post fetch request to get all of the users information
## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

<img width="198" alt="Screenshot 2023-06-07 at 1 33 35 AM" src="https://github.com/Lambpato/LSP/assets/34325124/385e33cc-7069-4e5e-a979-05936c7c303f">
<img width="507" alt="Screenshot 2023-06-07 at 1 33 18 AM" src="https://github.com/Lambpato/LSP/assets/34325124/a3f59f4b-f115-47da-b0a9-fe8dfeec1abd">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new component that
    - [x] Makes a fetch request 
    - [x] Store the information in a useState 
    - [x] Map through the useState place them in an unordered list containing the name and length of the song
  
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
