### ISSUE TITLE
Issue 9: User can play a song

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can play a song upon clicking 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Ill be updating the Songs component as well as creating media control component

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="335" alt="Screenshot 2023-06-08 at 1 23 45 PM" src="https://github.com/Lambpato/LSP/assets/34325124/af641101-4f61-4261-8f64-2e8cad3a43de">
<img width="335" alt="Screenshot 2023-06-08 at 1 24 01 PM" src="https://github.com/Lambpato/LSP/assets/34325124/c3f6704a-e4e5-4d1b-88ff-260a6963ba8c">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component named MediaPlayer to 
    - [x] Display media controls
    - [x] Create custom function to skip
    - [x] Create custom function to pause
    - [x] Create custom function to play back
    - [x] Scroll wheel must work 
- [x] Update component to add the new component to the Songs return 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
