### ISSUE TITLE
Issue 10: User can delete a song

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Same as user being able to delete a picture taken, user can now delete a saved song

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="335" alt="Screenshot 2023-06-16 at 12 54 41 AM" src="https://github.com/Lambpato/LSP/assets/34325124/faa25a36-6f2b-4931-9fa9-2bacab14448b">
<img width="335" alt="Screenshot 2023-06-16 at 12 54 59 AM" src="https://github.com/Lambpato/LSP/assets/34325124/03df52d8-3657-4137-820d-4a90d4ca6ac4">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update songs component 
   - [x] import delete modal
   - [x] reuse same function as the delete image component 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
