### ISSUE TITLE
Bug Fix 1: Fixing NavBar Back Button

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#20]
#### Desired Behavior

> ##### The app should ...

App should return to the previous page when clicked

#### Actual Behavior

> ##### The app does this instead ...

literally nothing

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

I click the button and nothing happens

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Check the NavBar function
- [x] Center the button
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
