### ISSUE TITLE
Bug Fix 2: Fixing Middleware Authentication 

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#22]
#### Desired Behavior

> ##### The app should return the user to the homepage when user is not signed in. Any other page component should not be accessible until logged in

#### Actual Behavior

> ##### The app does this instead, it allows the user to log in but even when not, the pages are still accessible.

#### Steps to Reproduce

> ##### To trigger the bug, you must be signed out and type in the URL of any of the pages, ex: http://localhost:3000/songs

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Check the server component, assure the userId is being assigned from req.params.userId
- [x] Make sure all get request are looking for the specific userId
- [x] Check to make sure the token is being stored in local storage
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
