### ISSUE TITLE
Refactor 1: Removing Test Code

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#25]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Update server.js parameters in all request.
- [x] Assure all URLs in express have userId included.
- [x] Update all fetch request urls to include userId
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
