### ISSUE TITLE
Issue 11: Users Have Guide

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#27]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to click on a certain action they would like to know how to preform and a list of steps will drop down, informing the user

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A accordion will be used to display the actions to the users, when an action is clicked, the list of steps will appear, if the same action is clicked again, that list will disappear, if another action is clicked when one is currently open the previous list will close and the new one will open

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to have an accordion with 
    - [x] How to Take a Selfie
    - [x] How to View Selfies 
    - [x] How to Delete a Selfie
    - [x] How to Add a New Song
    - [x] How to View Library
    - [x] How to Delete a song
- [x] Create a GuidePage.jsx component with Navbar and newly created component.
- [x] Update App.js component to include GuidePage.jsx component in react routing.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
