### ISSUE TITLE
Issue 1-2: User Can Register And Log In

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to register for a new account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="280" alt="Screenshot 2023-04-19 at 12 28 13 PM" src="https://user-images.githubusercontent.com/34325124/233179952-55ab7a7c-baa7-4550-a34d-fc08d79144fb.png">
<img width="605" alt="Screenshot 2023-04-19 at 12 28 38 PM" src="https://user-images.githubusercontent.com/34325124/233180030-bdcf221d-d59e-4ba8-a986-d4fd2730c3ca.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a form with proper css
- [x] Assure to test the form

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
