### ISSUE TITLE
Issue 3: Home Screen

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user is logged in they will be introduced to a manual carousel, depending on what the user is hovered over a set of features will display. Another carousel going vertically will be used for those features

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="663" alt="Screenshot 2023-04-24 at 3 18 48 PM" src="https://user-images.githubusercontent.com/34325124/234128814-7418f781-7596-4260-9304-e8ce9eda208b.png">
<img width="663" alt="Screenshot 2023-04-24 at 3 14 49 PM" src="https://user-images.githubusercontent.com/34325124/234128836-64c15175-38c6-4ab1-8a47-e670f060f271.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Add the current time to the top right
- [x] Create a component for the horizontal carousel
    - [x] Add the icons 
    - [x] Selected icon must be in the middle 
    - [x] Selected icon but be larger
- [x] Create a component for the vertical carousel
    - [x] Add the icons
    - [x] Selected icon must have highlight gradient

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
