### ISSUE TITLE
Issue 4: User can take a selfie 

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After clicking on the camera icon a screen displaying the camera with 2 buttons, a shutter button which will take the picture store it in the data base and a local file and the other being the back button, returning the user to the previous page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="442" alt="Screenshot 2023-04-26 at 2 24 55 PM" src="https://user-images.githubusercontent.com/34325124/234761184-4eea3eab-f2d0-4f00-941c-b8e4ad4c4135.png">
<img width="814" alt="Screenshot 2023-04-26 at 2 24 25 PM" src="https://user-images.githubusercontent.com/34325124/234761199-f21a95d0-d10f-4ef3-9a21-73ea47999d83.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to store the date the picture was taken rather than a caption

### ⚡ Client Tasks

- [ ] Create a component to show the camera
    - [x] npm install the required packages
    - [ ] create a new jsx file for the component
        - [x] import Webcam from 'react-webcam'
        - [x] import useRef 
        - [x] inside create a constraints object
            - [x] create width property and set it to 1080
            - [x] create a height property and set to 1080
            - [x] create a facingMode property with the value of "user"  
        - [x] set useRef to null and assign it to a variable
        - [x] call the Webcam import inside the return
            - [x] pass false through the audio prop
            - [x] pass 1080 through the height prop
            - [x] pass  the useRef variable previously created to the ref prop
            - [x] pass "image/png" to the prop screenshotFormat
            - [x] pass 1080 for the width prop
            - [x] pass the constraints variable through the videoConstraints prop
- [x] Create a function with a fetch request of post
- [x] Create a button and pass the previous function in the onClick

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
