### ISSUE TITLE
Issue 5: User can view selfies taken

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/LSP#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The date and time of the foto taken , once the user clicked on the date the image will pop up in a larger view
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="799" alt="Screenshot 2023-04-27 at 9 13 58 PM" src="https://user-images.githubusercontent.com/34325124/235057471-a154cd8e-0e97-4e79-a59b-71fcbe60b1f9.png">
<img width="602" alt="Screenshot 2023-04-27 at 9 33 12 PM" src="https://user-images.githubusercontent.com/34325124/235057485-a477698d-ce0f-48df-86e5-bbab42d1398b.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 server Tasks

- [x] Update `server.js` to return the date and the image id 

### ⚡ Client Tasks

- [x] Create a component to display the image dates
    - [x] import useState and useEffect
    - [x] create a useState with images and setImages
    - [x] create a use effect 
        - [x] create  function that 
        - [x] has a fetch request with the endpoint ('/api/images/'), ensure it contains the authorization token
        - [x] updates setImages
    - [x] returns a div that
       - [x] has another div with the image and title 
       - [x] has a div with the list containing the date and a broken img icon
- [x]  Create a component that has the NavBar and the newly created component

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
